export class Score {
    scoreId: number;
    personId: number;
    clubId: number;
    sanctionId: number;
    eventId: string;
    programId: string;
    resultSetId: number;
    sessionId: string;
    sessionSort?: any;
    difficulty?: any;
    execution?: any;
    deductions?: any;
    attempt?: any;
    score1?: any;
    score2?: any;
    score3?: any;
    score4?: any;
    score5?: any;
    score6?: any;
    finalScore: string = "0.0";
    rankSort?: any;
    rank?: number;
    tie: boolean = false;
    bibNumber: number;
    place: string;
    lastUpdate: Date;
    combinedScore?: any;
    combinedSessionId1?: any;
    combinedSessionId2?: any;
    combinedSessionId3?: any;
    combinedSessionId4?: any;
    combinedSession1Score?: any;
    combinedSession2Score?: any;
    combinedSession3Score?: any;
    constructor(opts: {
        scoreId: number;
        personId: number;
        clubId: number;
        sanctionId: number;
        eventId: string;
        programId: string;
        resultSetId: number;
        sessionId: string;
        sessionSort?: any;
        difficulty?: any;
        execution?: any;
        deductions?: any;
        attempt?: any;
        score1?: any;
        score2?: any;
        score3?: any;
        score4?: any;
        score5?: any;
        score6?: any;
        finalScore: string;
        rankSort?: any;
        rank?: number;
        tie: boolean;
        bibNumber: number;
        place: string;
        lastUpdate: Date;
        combinedScore?: any;
        combinedSessionId1?: any;
        combinedSessionId2?: any;
        combinedSessionId3?: any;
        combinedSessionId4?: any;
        combinedSession1Score?: any;
        combinedSession2Score?: any;
        combinedSession3Score?: any;
    }) {
        this.scoreId = opts.scoreId;
        this.personId = opts.personId;
        this.clubId = opts.clubId;
        this.sanctionId = opts.sanctionId;
        this.eventId = opts.eventId;
        this.programId = opts.programId;
        this.resultSetId = opts.resultSetId;
        this.sessionId = opts.sessionId;
        this.sessionSort = opts.sessionSort ?? undefined;
        this.difficulty = opts.difficulty ?? undefined;
        this.execution = opts.execution ?? undefined;
        this.deductions = opts.deductions ?? undefined;
        this.attempt = opts.attempt ?? undefined;
        this.score1 = opts.score1 ?? undefined;
        this.score2 = opts.score2 ?? undefined;
        this.score3 = opts.score3 ?? undefined;
        this.score4 = opts.score4 ?? undefined;
        this.score5 = opts.score5 ?? undefined;
        this.score6 = opts.score6 ?? undefined;
        this.finalScore = opts.finalScore ?? "0.0";
        this.rankSort = opts.rankSort ?? undefined;
        this.rank = opts.rank ?? 1;
        this.tie = opts.tie ?? false;
        this.bibNumber = opts.bibNumber;
        this.place = opts.place ?? "1"
        this.lastUpdate = opts.lastUpdate ?? new Date();
        this.combinedScore = opts.combinedScore ?? undefined;
        this.combinedSessionId1 = opts.combinedSessionId1 ?? undefined;
        this.combinedSessionId2 = opts.combinedSessionId2 ?? undefined;
        this.combinedSessionId3 = opts.combinedSessionId3 ?? undefined;
        this.combinedSessionId4 = opts.combinedSessionId4 ?? undefined;
        this.combinedSession1Score = opts.combinedSession1Score ?? undefined;
        this.combinedSession2Score = opts.combinedSession2Score ?? undefined;
        this.combinedSession3Score = opts.combinedSession3Score ?? undefined;
    }
}